### ISSUE TITLE
Add support for OFSI Consolidated List Search 

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/watchman#424] opened 2022-05-24 12:44 UTC
This is a meta-issue for including this list into search results. There are several lists to include, so we should plan how to add these.

Docs: https://sanctionssearchapp.ofsi.hmtreasury.gov.uk/

Questions:
- New endpoint?
- Do we need any additional parsing for UK specific formats?
- **How can we download this data?** API requests for each search will be slow.

**Comment by bryanuhri** [comment] 2022-08-17 14:30
This may be a duplicate of https://github.com/moov-io/watchman/issues/183.

**Closed** 2022-08-17 15:15 UTC
Labels: help wanted, question
