### ISSUE TITLE
Question: can we support the sanction list related to crypto address

### ISSUE THREAD

**Issue by merlintang** [moov-io/watchman#471] opened 2023-01-20 02:25 UTC
Watchman Version: ``

**What were you trying to do?**
We hope this server to provide crypto address  for the sanction list? 

**What did you expect to see?**

**What did you see?**

**How can we reproduce the problem?**

**Comment by merlintang** [comment] 2023-01-20 02:25
thanks for your efforts

**Comment by adamdecaf** [comment] 2023-01-20 18:05
Yes @merlintang I'm interested in supporting crypto addresses. I'm not sure what the best method (or source(s)) of addresses to block are, but am open to ideas. We're tracking this in https://github.com/moov-io/watchman/issues/362 and would appreciate your help. 

Duplicate of https://github.com/moov-io/watchman/issues/362

**Closed by adamdecaf** 2023-01-20 18:05 UTC
